language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t dktsudgg/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true dktsudgg/react-test-app npm run test

after_success:
  - docker build -t dktsudgg/docker-frontend ./frontend
  - docker build -t dktsudgg/docker-backend ./backend
  - docker build -t dktsudgg/docker-nginx ./nginx
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  - docker push dktsudgg/docker-frontend
  - docker push dktsudgg/docker-backend
  - docker push dktsudgg/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-fullstack-app"
  env: "Dockerfullstackapp-env-1"
  bucket_name: elasticbeanstalk-ap-northeast-2-879323555770
  bucket_path: "docker-fullstack-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY